# Exported from Render on 2024-10-24T23:26:58Z
services:
- type: web
  name: employee-management-backend
  runtime: docker
  repo: https://github.com/lancedalanon/employee-management-backend
  plan: free
  envVars:
  - key: APP_ENV
    sync: false
  - key: AWS_ENDPOINT
    sync: false
  - key: AWS_URL
    sync: false
  - key: AWS_USE_PATH_STYLE_ENDPOINT
    sync: false
  - key: AWS_BUCKET
    sync: false
  - key: AWS_DEFAULT_REGION
    sync: false
  - key: AWS_SECRET_ACCESS_KEY
    sync: false
  - key: AWS_ACCESS_KEY_ID
    sync: false
  - key: FILESYSTEM_DISK
    sync: false
  - key: APP_URL
    sync: false
  - key: AUTH_PASSWORD_RESET_TOKEN_TABLE
    sync: false
  - key: JWT_SECRET
    sync: false
  - key: VITE_APP_NAME
    sync: false
  - key: MAIL_FROM_NAME
    sync: false
  - key: MAIL_FROM_ADDRESS
    sync: false
  - key: MAIL_ENCRYPTION
    sync: false
  - key: MAIL_PASSWORD
    sync: false
  - key: MAIL_USERNAME
    sync: false
  - key: MAIL_PORT
    sync: false
  - key: MAIL_HOST
    sync: false
  - key: MAIL_MAILER
    sync: false
  - key: REDIS_PORT
    sync: false
  - key: REDIS_PASSWORD
    sync: false
  - key: REDIS_HOST
    sync: false
  - key: REDIS_CLIENT
    sync: false
  - key: MEMCACHED_HOST
    sync: false
  - key: CACHE_PREFIX
    sync: false
  - key: CACHE_STORE
    sync: false
  - key: QUEUE_CONNECTION
    sync: false
  - key: BROADCAST_CONNECTION
    sync: false
  - key: SESSION_SECURE_COOKIE
    sync: false
  - key: SESSION_DOMAIN
    sync: false
  - key: SESSION_PATH
    sync: false
  - key: SESSION_ENCRYPT
    sync: false
  - key: SESSION_LIFETIME
    sync: false
  - key: SESSION_DRIVER
    sync: false
  - key: DB_PASSWORD
    sync: false
  - key: DB_USERNAME
    sync: false
  - key: DB_DATABASE
    sync: false
  - key: DB_PORT
    sync: false
  - key: DB_HOST
    sync: false
  - key: DB_CONNECTION
    sync: false
  - key: LOG_LEVEL
    sync: false
  - key: LOG_DEPRECATIONS_CHANNEL
    sync: false
  - key: LOG_STACK
    sync: false
  - key: LOG_CHANNEL
    sync: false
  - key: BCRYPT_ROUNDS
    sync: false
  - key: APP_MAINTENANCE_STORE
    sync: false
  - key: APP_MAINTENANCE_DRIVER
    sync: false
  - key: APP_FAKER_LOCALE
    sync: false
  - key: APP_FALLBACK_LOCALE
    sync: false
  - key: APP_LOCALE
    sync: false
  - key: APP_TIMEZONE
    sync: false
  - key: APP_DEBUG
    sync: false
  - key: APP_KEY
    sync: false
  - key: APP_NAME
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
