name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, sqlite3, dom, fileinfo

      - uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "APP_ENV=testing" >> $GITHUB_ENV
          echo "DB_CONNECTION=sqlite" >> $GITHUB_ENV
          echo "JWT_SECRET=your_jwt_secret" >> $GITHUB_ENV

      - name: Install Composer dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Copy .env
        run: cp .env.example .env

      - name: Run migrations
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan migrate --force

      - name: Run tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: |
          php artisan test --env=testing --verbose --debug
