name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring 
        coverage: none
    
    # Checkout the repository
    - uses: actions/checkout@v4

    # Cache composer dependencies to speed up builds
    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
    
    # Install Composer dependencies
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    # Copy .env.example if .env does not exist
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    
    # Generate the application key
    - name: Generate key
      run: php artisan key:generate

    # Set directory permissions
    - name: Set Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    # Ensure the database is ready (Run migrations)
    - name: Run migrations
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: ":memory:"
      run: php artisan migrate --force

    # Run the tests
    - name: Run Tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: :memory:
      run: php artisan test --colors
