name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, sqlite3, dom, fileinfo

      # Cache Composer dependencies for faster builds
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      # Install Composer dependencies
      - name: Install Composer dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      # Set environment variables for testing
      - name: Set environment variables
        run: |
          echo "APP_ENV=testing" >> $GITHUB_ENV
          echo "DB_CONNECTION=sqlite" >> $GITHUB_ENV
          echo "JWT_SECRET=your_jwt_secret" >> $GITHUB_ENV

      # Copy .env.example and prepare the environment
      - name: Copy .env
        run: cp .env.example .env

      # Generate APP_KEY (required for Crypt and other encrypted functions)
      - name: Generate application key
        run: php artisan key:generate

      # Create SQLite database
      - name: Prepare SQLite database
        run: |
          touch database/database.sqlite

      # Run migrations for testing
      - name: Run migrations
        run: php artisan migrate --force

      # Run tests
      - name: Run tests
        run: php artisan test --env=testing --debug
